services:
    -type: web
    name: flask-r-app
    env: python
    buildCommand: |
        apt-get update
        apt-get install -y r-base
        pip install -r requirements.txt
    startCommand: gunicorn app:app 